## Libraries
library(dplyr)
library(ggplot2)
library(stringr)
library(tidyselect)
## Smoothing the estimated active cases
## Uses the files generated by the scripts UMD_XX_country_analysis_batches.R
`%notin%` <- Negate(`%in%`)
source("smooth_column_past.R")
smooth_param <- 15

file_in_path <- "../data/UMD_updated/Full Survey Data/country" #../data/estimates-umd-batches/"
file_in <- ".*_country_full.csv" #"_UMD_country_data.csv"
file_out_path <- "../data/estimates-umd-unbatched/PlotData/"
file_out <- "_UMD_country_nobatch_past_smooth.csv"

populationfile <-"../data/common_data/country_population_umd.csv"
popdt <- read.csv(populationfile,fileEncoding = "UTF-8")

countriesToExclude <- c("AFG", "ALB", "ASM", "BEN", "BFA" )
countriesDone <- c("AGO", "ARE", "ARG", "ARM", "AUS", "AUT", "AZE" , "BEL")
countriesToExclude <- c(countriesToExclude, countriesDone)

files <- dir(file_in_path,pattern=file_in)


#print (files)

pct_excluded <- c()
pct_to_smooth <- c("pct_cli",
                   "pct_ili",
                   "pct_fever",
                   "pct_cough",
                   "pct_difficulty_breathing",
                   "pct_fatigue",
                   "pct_stuffy_runny_nose",
                   "pct_aches_muscle_pain",
                   "pct_sore_throat",
                   "pct_chest_pain",
                   "pct_nausea",
                   "pct_anosmia_ageusia",
                   "pct_eye_pain",
                   "pct_headache",
                   "pct_cmnty_sick",
                   "pct_ever_tested",
                   "pct_tested_recently",
                   "pct_worked_outside_home",
                   "pct_grocery_outside_home",
                   "pct_ate_outside_home",
                   "pct_spent_time_with_non_hh",
                   "pct_attended_public_event",
                   "pct_used_public_transit",
                   "pct_direct_contact_with_non_hh",
                   "pct_wear_mask_all_time",
                   "pct_wear_mask_most_time",
                   "pct_wear_mask_half_time",
                   "pct_wear_mask_some_time",
                   "pct_wear_mask_none_time",
                   "pct_no_public",
                   "pct_feel_nervous_all_time",
                   "pct_feel_nervous_most_time",
                   "pct_feel_nervous_some_time",
                   "pct_feel_nervous_little_time",
                   "pct_feel_nervous_none_time",
                   "pct_feel_depressed_all_time",
                   "pct_feel_depressed_most_time",
                   "pct_feel_depressed_some_time",
                   "pct_feel_depressed_little_time",
                   "pct_feel_depressed_none_time",
                   "pct_worried_ill_covid19_very",
                   "pct_worried_ill_covid19_somewhat",
                   "pct_worried_ill_covid19_notTooWorried",
                   "pct_worried_ill_covid19_notWorried",
                   "pct_enough_toEat_very_worried",
                   "pct_enough_toEat_somewhat_worried",
                   "pct_enough_toEat_notToo_worried",
                   "pct_enough_toEat_not_worried",
                   "pct_chills",
                   "pct_finances_very_worried",
                   "pct_finances_somewhat_worried",
                   "pct_finances_notToo_worried",
                   "pct_finances_not_worried")

for (filename in files){
  tryCatch({
  iso3=toupper(substr(filename,1,3))
  if (iso3  %notin% countriesToExclude ){
    #print (toupper(iso2))
    rowPop=popdt[popdt$iso_alpha3==iso3,]
    #print(rowPop)
    iso2=toString(rowPop[['iso_alpha2']])
    population=rowPop[['population']]
    #print(population)
    cat("Country:", iso3, " ", iso2, "\n")
    ## Load data ----
    #filename <- paste0(iso3,file_in)
    dtunfiltered <- read.csv(paste0(file_in_path,"/",filename),
                             fileEncoding = "UTF-8")
    
    dt=filter(dtunfiltered, gender == "overall" &  age_bucket == "overall")
    #print(dt)
    
    dt$date <- as.Date(dt$date)
    
    
    dt0 <- dt %>% select(date, total_responses)
    dt1 <- dt %>% select(date, all_of(pct_to_smooth))
    dtn <- dt %>% select(date, all_of(pct_excluded))
    
    for (pct in pct_to_smooth){
      #cat("Signal:", pct, "\n")
      dt1 <- smooth_column_past(df_in = dt1,
                                col_s =  pct,
                                basis_dim = smooth_param,
                                link_in = "log",
                                monotone = F,
                                conf_interval = F)
    }
    
    dt_out <- merge(dt0, dt1, by="date")
    dt_out <- merge(dt_out, dtn, by="date")
    dt_out['population']=population
    write.csv(dt_out, paste0(file_out_path, iso2, file_out),
              row.names = FALSE)
    # plot(dt$date, dt$pct_ili_past_smooth)
  } else {
    print(paste("excluding country",iso3))
  }
  }, error=function(cond) {
    message(paste("error in country", iso3))
    message("Here's the original error message:")
    message(cond)
  })
}
